### ISSUE TITLE
Autolicensing and text-editor options

### ISSUE THREAD

**Issue by MartinLunn** [LunCol/OH4L#2]
Is there an option in whatever text-editor we use to automatically include the license in every source file that's ours?

GPL recommends we include a pointer or a reference of sorts (even just a textual one) to our license. Is there a way to automatically have a text editor include that?

Specifically it just wants a short blurb commented out in every source file at the top.

**Comment by MartinLunn** [comment]
Also, if we do any terminal interaction, we should also include a quick blurb on startup or something.

Presumably we'll have to take user input and give users output somehow...a GUI would be nice, but at some point it'll be terminal probably.

**Comment by Chris1221** [comment]
License file in the root dir apply to all files in all branches
automatically :)

**Comment by MartinLunn** [comment]
So it'll be auto-included? Or just applies generally?

**Comment by Chris1221** [comment]
Applies generally, not included. I think that's just how github works.
Also we'll make a CLI first with a --help / -h option and include all of
that on the readme with all arguments. That's easy to do in Python and is
convention

**Comment by Chris1221** [comment]
After that we can wrap up into a gui, but definitely CLI first :)

**Comment by MartinLunn** [comment]
How much effort would it take to include the boilerplate license reference in every source (preferably automatically)?

Also sweet about the CLI, sounds like a plan.

In terms of best practices, is starting an Issue, and posting comments like this a good approach?
Are there better ones?

**Comment by Chris1221** [comment]
Not much :). Not sure about automatically, but could add a comment at the top of each file referencing the .license file :) 

Yea! This is perfect and exactly how we should use it :). To keep record of all convo about this here if we want to go back :)

**Comment by Chris1221** [comment]
When you add the license, we commit and say "close #2" and it will show that we closed this issue with that commit :)

**Comment by MartinLunn** [comment]
Hmm. I wanna add the license to the repo itself too.
Like this guy did.
https://github.com/ryanseys/carleton-grades
Just a "GPLv3 as referenced in license.md."

**Comment by MartinLunn** [comment]
I can't find the option :(

**Comment by MartinLunn** [comment]
I'm also considering making a repo for every comsci class I have/have had
I'm really not sure how I want the architecture to work, because it makes more sense to have 1 repo per assignment, but that seems like WAY too much effort.

**Comment by Chris1221** [comment]
I don't think there is an option, I think he just wrote that :) Do you want me to make a license file for GPLv3? 

Also that's a really good idea :) Yea, I would just make a folder per assignemnt / topic. Maybe make a private repo (from the github student thing) just so other people can't find your stuff and copy it :) and if youre working with people on an assignment you can like, invite them to it, then after its handed in make the repo public so thatyou don't use up your 5 private repos :) thats what I would do anyway!

**Comment by MartinLunn** [comment]
I'm gonna go ahead and update your file to call it License.md, and delete mine. :)

What's the enhancement?

**Comment by MartinLunn** [comment]
https://creativecommons.org/licenses/by-nc-sa/3.0/

This is what I was thinking of, but I guess that's for art, eh?

**Comment by Chris1221** [comment]
I think we shouldn't worry about the license so much :) Realistically we might get a few random hits, and even if someone copies the code it's not going to matter that much :) Maybe when we have a finished app then we can lock it down, but until then I think we're overthinking this :)
